export enum SubContractActivityType {
  ProjectAccepted = 'PROJECT_ACCEPTED',
  ProjectDeclined = 'PROJECT_DECLINED',
  SiteVisited = 'SITE_VISITED',
  Excavated = 'EXCAVATED',
  GradeSet = 'GRADE_SET',
  BaseInstalled = 'BASE_INSTALLED',
  Screeded = 'SCREEDED',
  HardscapeInstalled = 'HARDSCAPE_INSTALLED',
  Adjusted = 'ADJUSTED',
  CleanedUp = 'CLEANED_UP',
  FinalPhotosTaken = 'FINAL_PHOTOS_TAKEN',
  MaterialReturned = 'MATERIAL_RETURNED',
  Milestone1PaymentRequested = 'MILESTONE_1_PAYMENT_REQUESTED',
  ApprovedMilestone1Payment = 'APPROVED_MILESTONE_1_PAYMENT',
  Milestone2PaymentRequested = 'MILESTONE_2_PAYMENT_REQUESTED',
  ApprovedMilestone2Payment = 'APPROVED_MILESTONE_2_PAYMENT',
}
